### PR TITLE
Dynamic Values Mod

### PR DESCRIPTION
**Pull request by high-the-memory**
Here is the code for automatically pulling info. Let me know what you think or if you have any issues in testing it.

### CODE REVIEW

**Comment by SethClydesdale** [comment]
I gave your modifications a quick test, but I'm having a few issues. When I download [your version](https://github.com/Paralax2062/psobb-drop-charts/archive/master.zip) of the repository I get an error in init.lua @ line 631. Moving those helper functions to the top helps, however, I then run into more issues with the coloring of the texts. I attempted replacing this line in TextC : 
```lua
imgui.TextColored(c.r, c.g, c.b, c.a, str)
```

With this to prevent any major errors from occurring : 
```lua
imgui.TextColored(c.r or 1, c.g or 1, c.b or 1, c.a or 1, str)
```

While it works, the text coloring doesn't. Do you have any idea why ? I haven't used the TextC helper function before, I only ever used imgui.TextColored()

**Comment by high-the-memory** [comment]
Hmm, it still worked for me when I copied soly's functions into the file so I didn't think about it, but I think it could be possibly the functions' scope? TextC() needs GetColorAsFloats(). I wasn't sure exactly how Lua handles forward declarations of functions. They are declared locally though, so perhaps:

Have you tried moving both of the declarations to the top, and then make sure that GetColorAsFloats() is declared above TextC()?
And or removing the [local] from the declaration (I would assume that would define them in the global scope of the script, and everything should be able to access them). 

What error is it giving you?

**Comment by SethClydesdale** [comment]
Yep that looks to be the issue ! I moved the helper functions to the top, however, I left `GetColorAsFloats` below `TextC` which seems to have been the cause of the error. Coming from JavaScript I'm used to functions being "hoisted", so I hadn't thought about the order the functions were defined being the issue haha.

Everything is running perfectly on my end now, thanks for looking into that. 👍 I'll merge your changes now, and I might change the DAR/RR to be on the same line so they don't take up too much room vertically.

Nice work ! 😄

**Comment by high-the-memory** [comment]
No problem 👍, the only thing I can think of is: the individual drop chart files had to be altered to extract dar/rr. If they are changed again, this would break. So either: could alter the script you use to generate these files, or I could add a function that extracts the dar/rr from those strings on the fly. (I just used regex find and replace to strip away what was unneeded)

**Comment by SethClydesdale** [comment]
Hmm.. I think the best option would be to alter the script that's used to grab the charts, so that it works with the new functionality you added. The part that would need to be modified is [line 69](https://gist.github.com/SethClydesdale/9b887d9bfedaf644d91d2350ec32db74#file-chart-grabber-js-L69). I assume we'd replace `tooltip` with `dar` and `rare`, then extract the dar/rare from `abbr.title` or `abbr.innerText`. I'll try to look into that tomorrow when I wake up, since it's getting kind of late here.

BTW I like the way you did it ; it reduced the size of the addon considerably.

**Comment by SethClydesdale** [comment]
The chart grabber script should be updated now. I removed the tooltip property and added the dar/rare properties instead. I noticed the boxes don't have rare rates in their tooltips, except for the percentages for the PSO*/2 drop rates. I think that's where you got the percentage, right ?

You can check my changes here to make sure : 
https://gist.github.com/SethClydesdale/9b887d9bfedaf644d91d2350ec32db74/revisions#diff-608a8e5927e3c739a4a365be57365ca8

Feel free to make any changes if needed. 👍

**Comment by high-the-memory** [comment]
Yes, dar for all boxes is 100% (for default), and the rare rate is the percent for PSO* 1P:...

Looks like you've got it; I can't test it at the moment, but: I don't think we want a string with "%%" part. I believe I utilize the raw numbers.

Will try to confirm, but I think we want the end result to be like:
```lua
{
  ["target"] = "Hildeblue/Hildetorr",
  ["item"] = "Resist/Fire",
  ["dar"] = 100,
  ["rare"] = 87.50000
}
```
etc.

**Comment by SethClydesdale** [comment]
Ah sorry, I hadn't noticed that haha. I updated the script to make sure that it [only captures the raw value](https://gist.github.com/SethClydesdale/9b887d9bfedaf644d91d2350ec32db74/revisions#diff-608a8e5927e3c739a4a365be57365ca8) and parses it as a float. The output looks like : 

```lua
      {
        ["target"] = "Hildeblue/Hildetorr",
        ["item"] = "Resist/Fire",
        ["dar"] = 100,
        ["rare"] = 87.5
      },
```

It looks like trailing zeros are trimmed out though. I guess that's a small caveat when converting a string to a number in js, but it shouldn't be a problem. If it is, I can always try to cook up a solution though. 😉

**Pull request merged**
